### ISSUE TITLE
MixingMetric

### ISSUE THREAD

**Issue by jhu99** [satijalab/Integration2019#1]
Hello,

MixingMetric was calculated by MixingMetric function or by max.k-MixingMetric(). 
As what I understood, MixingMetric() will return the final result.
but, the code in your script is mm = max.k - MixingMetric . 
Could you tell me how should I use this function?

Thanks,
Jialu

**Comment by andrewwbutler** [comment]
Hi Jialu,

Sorry for the delayed response. The `MixingMetric` function tries to assess the local neighborhood composition for a cell and how well mixed that neighborhood is. The idea is that if the neighborhood is well mixed, then it should contain at least some cells from each dataset. The way that we calculate this is as follows:

1. Look at the `k.max` nearest neighbors for a cell across all datasets. 
2. Compute the `k` closest neighbors for each dataset individually for the same cell. 
3. Find the rank in the overall neighborhood list (from 1.) that corresponds to the `kth` neighbor in each dataset (max of k.max) and take the median across all datasets.
4. Compute 1-3 for every cell and average. 

This average is the value that is returned by the `MixingMetric` function. However, it's usually more intuitive to think of high values of "mixing" to be better so for visualization, we often plot `max.k - MixingMetric`.
