### ISSUE TITLE
Trouble determining differentially expressed genes among conditions

### ISSUE THREAD

**Issue by aelias1** [satijalab/Integration2019#4]
Hello,

I have posted about this before, but I'm still having trouble.  I am trying to see which genes are most different between my conditions in one cluster.  Here is my code and error. 

svzyoung$celltype.gender <- paste(Idents(svzyoung), svzyoung$orig.ident, sep = "&")
svzyoung$celltype.gender <- Idents(svzyoung)
Idents(svzyoung) <- "celltype.gender"
diff.gender.astro <- FindMarkers(svzyoung, ident.1 = "Astro&SVZ_Young_Female", ident.2 = "Astro&SVZ_Young_Male", verbose = FALSE)
head(diff.gender.astro, n = 15)

Error in WhichCells.Seurat(object = object, idents = ident.1) : 
  Cannot find the following identities in the object: Astro&SVZ_Young_Female

I have tried sep="_" as well.

**Comment by timoast** [comment]
Hi, sorry for the delay, this repo is not monitored closely. I think you meant to raise this issue in the [Seurat repository](https://github.com/satijalab/seurat), I suggest you create a new issue there if you're still having trouble
